### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by Cr3am** [mathieulandrain/No-Limit-v2#3]
instances of mute kick and ban do not work correctly the console reports the error of
TypeError: message.guild.createRole is not a function
    at Object.module.exports.run (/ home / container / cmds / 🚨 - Moderation / mute.js: 27: 38)
    at Client. <anonymous> (/home/container/main.js:94:32)
    at Client.emit (events.js: 315: 20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js: 315: 20)
(node: 2943) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.run (/ home / container / cmds / 🚨 - Moderation / mute.js: 45: 28)
    at Client. <anonymous> (/home/container/main.js:94:32)
    at Client.emit (events.js: 315: 20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js: 315: 20)
(node: 2943) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)

**Comment by mathieulandrain** [comment]
Update the code, my code is old.
